### ISSUE TITLE
Game does not work after applying patch

### ISSUE THREAD

**Issue by ghost** [sergeii/swat-patches#2]
Hi. I did a clean installation of the game (gold version), but installed the dll of each version, when trying to start the game everything becomes black and I get an error message:

**Swat 4**

No Label

Crash Time: 02/12/18 19:01:33

OS: Windows NT 6.2 (Build: 9200)
CPU: GenuineIntel PentiumPro-class processor @ 3494 MHz with 2047MB RAM
Video: NVIDIA GeForce GTX 1080 (9065)

UserName: mario
ComputerName: DESKTOPAMOBJ0T
Application location: C:\GOG Games\SWAT 4\Content\System\

SWAT Build Number: 34688

Error setting display mode: CreateDevice failed (D3DERR_INVALIDCALL). Please delete your Swat4.ini file if this error prevents you from starting the game.

History: UD3DRenderDevice::UnSetRes <- CreateDevice <- UD3DRenderDevice::SetRes <- HandleBigChange <- UD3DRenderDevice::Lock <- UViewport::Lock <- UWindowsViewport::Lock <- PrecacheRenderData <- Precaching <- UGameEngine::Draw <- UWindowsViewport::Repaint <- UWindowsClient::Tick <- ClientTick <- UGameEngine::Tick <- UpdateWorld <- MainLoop->GenerateExtraCrashInfo [(GLevel: 'myLevel' PendingLevel: '(NULL)' NetMode: 'NM_Standalone'] <- MainLoop

**Swat 4X**

No Label

Crash Time: 02/12/18 19:03:12

OS: Windows NT 6.2 (Build: 9200)
CPU: GenuineIntel PentiumPro-class processor @ 3494 MHz with 2047MB RAM
Video: NVIDIA GeForce GTX 1080 (9065)

UserName: mario
ComputerName: DESKTOPAMOBJ0T
Application location: C:\GOG Games\SWAT 4\ContentExpansion\System\

SWAT Build Number: 1.0

Error setting display mode: CreateDevice failed (D3DERR_INVALIDCALL). Please delete your Swat4X.ini file if this error prevents you from starting the game.

History: UD3DRenderDevice::UnSetRes <- CreateDevice <- UD3DRenderDevice::SetRes <- HandleBigChange <- UD3DRenderDevice::Lock <- UViewport::Lock <- UWindowsViewport::Lock <- PrecacheRenderData <- Precaching <- UGameEngine::Draw <- UWindowsViewport::Repaint <- UWindowsClient::Tick <- ClientTick <- UGameEngine::Tick <- UpdateWorld <- MainLoop->GenerateExtraCrashInfo [(GLevel: 'myLevel' PendingLevel: '(NULL)' NetMode: 'NM_Standalone'] <- MainLoop

Without the patch the game works perfectly.

**EDIT**: problem fixed just using compatibility mode.

**Comment by BaDTimE-S4** [comment]
Those files contains 'No CDKEY' patch and also multiple vulnerabilities fixes credited to the researcher Luigi Auriemma, what is needed only in public servers.

I recommend edit HOSTS file, as shown in this video: https://vimeo.com/172786167 , if the problem persist.

For further support, pls try Swat4 Discord Group: https://discord.gg/v7WnaPm
