### ISSUE TITLE
server list not visible

### ISSUE THREAD

**Issue by Light800** [sergeii/swat-patches#3]
Hello, I have the GOG version and after installing the patch the server list is still empty

**Comment by BaDTimE-S4** [comment]
I just tested it and everything is working fine: https://cdn.discordapp.com/attachments/244169425111089162/459647457404387329/Shot00000.png

For further support, pls try Swat4 Discord Group: https://discord.gg/v7WnaPm

**Comment by sergeii** [comment]
The server list was indeed offline at May 28th due to host issues. This patch is working as intended ;-)
